import { Inter } from "next/font/google";
import Link from "next/link";
import "./style.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="nav-container">
          <Link href={'/'}>Home</Link>
          <ul>
            <li>Contact</li>
            <li>Blog</li>
          </ul>
        </div>
        {children}
        <div className="footer-container">
          <Link href={'/'}>Home</Link>
        </div>
      </body>
    </html>
  );
}
